version: '3.8'
services:
  matters-backend:
    build: 
      context: backend 
    image: "${COMPOSE_PROJECT_NAME}-backend"
    hostname: "${COMPOSE_PROJECT_NAME}-backend" 
    restart: unless-stopped
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    container_name: "${COMPOSE_PROJECT_NAME}-backend"
    command: "/usr/bin/supervisord -c /etc/supervisor/supervisord.conf"
      #    command: ["pm2-runtime", "/opt/backend-git-deploy/process.yml"]
      # command: "pm2 logs -f"
    environment: 
      - CELERY_BROKER_URL=${REDIS_HOST}:6379/0
      - CELERY_RESULT_BACKEND=${REDIS_HOST}:6379/1
      - DOCKER_HOST=${DOCKER_HOST}
      - DATABASE_URL=${POSTGRES_URL}
    links: 
      - redis
    depends_on:
      - redis
      - postgres
    networks:
      default:
        ipv4_address: "${BACKEND_IPV4}"
        aliases:
          - "${COMPOSE_PROJECT_NAME}-backend"
    volumes:
      - "${BACKEND_VOL}:/opt/backend"
        #      - git-deployments:/tmp
      - nginx-confs:/nginx-confs
  redis:
    container_name: "${COMPOSE_PROJECT_NAME}-redis"
    image: "${REDIS_IMAGE}"
    hostname: "${COMPOSE_PROJECT_NAME}-redis"
    ports: []
    networks: 
      default:
        ipv4_address: "${REDIS_IPV4}"
        aliases:
          - "${COMPOSE_PROJECT_NAME}-redis"
  frontend:
    build:
      context: frontend
    image: "${COMPOSE_PROJECT_NAME}-frontend"
    hostname: "${COMPOSE_PROJECT_NAME}-frontend"
    restart: unless-stopped
    ports: []
      #command: ["pm2-runtime","/opt/git-deploy-frontend/process.yml"]
      #command: ["npm","run","dev"]
    command: "/usr/bin/supervisord -c /etc/supervisor/supervisord.conf"
    container_name: "${COMPOSE_PROJECT_NAME}-frontend"
    links: 
      - "${COMPOSE_PROJECT_NAME}-backend"
    depends_on:
      - "${COMPOSE_PROJECT_NAME}-backend"
    environment: []
    volumes: 
      - "${FRONTEND_VOL}:/opt/frontend"
    networks:
      default:
        ipv4_address: "${FRONTEND_IPV4}"
        aliases:
          - "${COMPOSE_PROJECT_NAME}-frontend"
  postgres:
    image: "${POSTGRES_IMAGE}"
    container_name: "${COMPOSE_PROJECT_NAME}-postgres"
    hostname: "${COMPOSE_PROJECT_NAME}-postgres"
    restart: unless-stopped
    ports: []
    environment: 
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWD}
      - PGDATA=/var/lib/postgresql/data/pgdata 
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      default:
        ipv4_address: "${POSTGRES_IPV4}"
    volumes:
      - "${POSTGRES_VOL}:/var/lib/postgresql/data"

networks:
  default:
    name: "${COMPOSE_PROJECT_NAME}"
    external: true
  deployment_network:
    ipam:
      driver: default
      config:
        - subnet: ${DEPLOYMENT_NETWORK}
volumes:
  nginx-confs:
    driver: local
    driver_opts:
      type: bind
      o: bind
      device: /opt/nginx-confs
